site_name: Football
site_author : Marcel Lhote
site_description : Site des match de Football.
repo_url: https://github.com/LhoMars/football
edit_uri: 'edit/main/docs/'

nav:
    - Home: index.md
    - Utilisation :
        - Panel admin: pages/admin.md
        - Utilisateur : pages/utilisateur.md

theme:
    name: material
    language: fr
    features:
        - navigation.top
        - toc.integrate
        - content.code.annotate
        - header.autohide
    palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: dracula
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: deep purple
      accent: deep purple
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css: [style/extra.css]

extra:
    generator: false

plugins:
    - search
    - mkdocs_pymdownx_material_extras

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets
    - footnotes
    - def_list
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tasklist:
        custom_checkbox: true